service: serverless-mathjs

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  profile: serverlessjs-deployer
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

functions:
  app:
    handler: server.handler
    warmup: {opt:stage, 'dev'}
    timeout: 30
    events:
      - http: ANY /v1
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
  - serverless-plugin-warmup

custom:
  warmup:
    memorySize: 128
    schedule: 'rate(15 minutes)'
    timeout: 20
    prewarm: true
